### PR TITLE
Endpoint is now alert.palette-software.com

### PR DESCRIPTION
**Pull request by baspeti**

### CODE REVIEW

**Comment by StephenHynes7** [comment]
@baspeti why change the end point? This would break the library completely

**Comment by baspeti** [comment]
@StephenHynes7 Oh, I'm terribly sorry, I pushed this change to the wrong (original) repository.

**Comment by DanielStolt** [comment]
This is one of the most amusing PRs I've seen in a long time. Set the endpoint to some random server? :)

**Comment by DanielStolt** [comment]
Aha, hehe @baspeti saw your comment too late.

**Comment by baspeti** [comment]
You guys are quick! :) I didn't have time to realize, that my PR was compared to the original master, and then I clicked. (But I guess you got notified.)

Anyway, I'm glad I could make you smile a bit.
Btw, LogEntries rocks! (But there are some typos in the NLog getting started page though... Are you interested about them?)

**Comment by StephenHynes7** [comment]
The title caught my eye. Sure if you have any thoughts on improving the doc here please let me know, I have become to used to it to notice these things :(

**Comment by szilardhuber** [comment]
Helping out @baspeti.
We are talking about this page:
https://logentries.com/doc/dotnet/

This line has typos: 
```private static readonly Logger m_logger = LogManager.getCurrentClassLogger();```

I think the correct one would be (capital L and capital G)
```private static readonly Logger m_Logger = LogManager.GetCurrentClassLogger();```

Also in here: ```private static readonly Logger m_Logger = LogManager.getCurrentClassLogger();
``` getCurrentClassLogger should begin with capital G

There are minor stuff but people like me who just copy-pastes lines from documentation would face compile errors immediately and that's a little scary as a first impression on a library.

**Pull request closed without merging**
